services:
  - type: web
    name: text-analyzer
    runtime: python
    buildCommand: |
      /opt/render/project/src/.venv/bin/python -m pip install --upgrade pip
      /opt/render/project/src/.venv/bin/pip install -r requirements.txt
      /opt/render/project/src/.venv/bin/python -m spacy download en_core_web_sm
      /opt/render/project/src/.venv/bin/python -m nltk.downloader punkt stopwords
    startCommand: gunicorn --worker-tmp-dir /dev/shm --bind :$PORT webapp:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: NLTK_DATA
        value: /opt/render/.cache/nltk_data
    plan: free