services:
  - type: web
    name: text-analyzer
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
      python -m nltk.downloader punkt stopwords
    startCommand: gunicorn --worker-tmp-dir /dev/shm --bind :$PORT webapp:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    plan: free
